providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["node .yarn/releases/yarn-3.2.2.cjs install"]

[start]
cmd = "node .yarn/releases/yarn-3.2.2.cjs workspace api start"
