export const CABA_PROVINCE_ALIASES = [
  "capital federal",
  "caba",
  "ciudad autonoma de buenos aires",
  "ciudad autónoma de buenos aires",
  "cfd",
];

export const GBA_PROVINCE_ALIASES = [
  "buenos aires",
  "pcia. buenos aires",
  "provincia de buenos aires",
  "gba",
];

export const GBA_LOCALITIES = [
  "avellaneda",
  "san isidro",
  "vicente lopez",
  "vicente lópez",
  "tigre",
  "san fernando",
  "san miguel",
  "malvinas argentinas",
  "jose c. paz",
  "josé c. paz",
  "tres de febrero",
  "moron",
  "morón",
  "hurlingham",
  "ituzaingo",
  "ituzaingó",
  "la matanza",
  "lanus",
  "lanús",
  "lomas de zamora",
  "quilmes",
  "berazategui",
  "florencio varela",
  "almirante brown",
  "esteban echeverria",
  "esteban echeverría",
  "ezeiza",
  "merlo",
  "moreno",
  "pilar",
  "escobar",
  "san martin",
  "san martín",
  "general san martin",
  "general san martín",
  "general rodriguez",
  "general rodríguez",
  "la plata",
  "marcos paz",
  "presidente peron",
  "presidente perón",
];
